In [86]:
import pandas as pd
import numpy as np 
import math as mt
from sklearn.linear_model import LinearRegression

In [87]:
df= pd.read_csv("hiring.csv")
df

experience  test_score(out of ten)  interview_score(out of ten)  salary($)
0        NaN                     8.0                            9      50000
1        NaN                     8.0                            6      45000
2       five                     6.0                            7      60000
3        two                    10.0                           10      65000
4      seven                     9.0                            6      70000
5      three                     7.0                           10      62000
6        ten                     NaN                            7      72000
7     eleven                     7.0                            8      80000

In [88]:
from word2number import w2n
print(w2n.word_to_num('two point three'))


2.3


In [89]:
df.experience=df.experience.fillna('zero')

In [90]:
df

experience  test_score(out of ten)  interview_score(out of ten)  salary($)
0       zero                     8.0                            9      50000
1       zero                     8.0                            6      45000
2       five                     6.0                            7      60000
3        two                    10.0                           10      65000
4      seven                     9.0                            6      70000
5      three                     7.0                           10      62000
6        ten                     NaN                            7      72000
7     eleven                     7.0                            8      80000

In [91]:
df.experience

0      zero
1      zero
2      five
3       two
4     seven
5     three
6       ten
7    eleven
Name: experience, dtype: object

In [92]:
df['test_score(out of ten)']

0     8.0
1     8.0
2     6.0
3    10.0
4     9.0
5     7.0
6     NaN
7     7.0
Name: test_score(out of ten), dtype: float64

In [93]:
import math
median = math.floor(df['test_score(out of ten)'].mean())
median

7

In [94]:
df['test_score(out of ten)'] = df['test_score(out of ten)'].fillna(median)

In [95]:
df

experience  test_score(out of ten)  interview_score(out of ten)  salary($)
0       zero                     8.0                            9      50000
1       zero                     8.0                            6      45000
2       five                     6.0                            7      60000
3        two                    10.0                           10      65000
4      seven                     9.0                            6      70000
5      three                     7.0                           10      62000
6        ten                     7.0                            7      72000
7     eleven                     7.0                            8      80000

In [96]:
from word2number import w2n
df.experience = df.experience.apply(w2n.word_to_num)
df

experience  test_score(out of ten)  interview_score(out of ten)  salary($)
0           0                     8.0                            9      50000
1           0                     8.0                            6      45000
2           5                     6.0                            7      60000
3           2                    10.0                           10      65000
4           7                     9.0                            6      70000
5           3                     7.0                           10      62000
6          10                     7.0                            7      72000
7          11                     7.0                            8      80000

In [99]:
reg= LinearRegression()
reg.fit(df[['experience','test_score(out of ten)','interview_score(out of ten)']],df['salary($)'])


LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [100]:
reg.coef_

array([2922.26901502, 2221.30909959, 2147.48256637])

In [101]:
reg.intercept_

14992.651446693118

In [102]:
reg.predict([[2,9,6]])

array([53713.86677124])

In [103]:
reg.predict([[12,10,10]])

array([93747.79628651])